### ISSUE TITLE
exception with summarize command

### ISSUE THREAD

**Issue by kspham** [roryk/bcbio.rnaseq#16]
Thanks Roryk for the great pipeline. But it just yields exception when I run summarize command. 
bcbio-rnaseq summarize  2015-07-15_rnaseq2/project-summary.yaml 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at bcbio.rnaseq.simulate$loading__4910__auto__.invoke(simulate.clj:1)
	at bcbio.rnaseq.simulate__init.load(Unknown Source)
	at bcbio.rnaseq.simulate__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at bcbio.rnaseq.core$loading__4910__auto__.invoke(core.clj:1)
	at bcbio.rnaseq.core__init.load(Unknown Source)
	at bcbio.rnaseq.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:415)
	at bcbio.rnaseq.core.<clinit>(Unknown Source)
Caused by: java.io.FileNotFoundException: /bin/bcbio-rnaseq!/comparisons/baseprop.tsv (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at clojure.java.io$fn__8642.invoke(io.clj:242)
	at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
	at clojure.java.io$fn__8650.invoke(io.clj:260)
	at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
	at clojure.java.io$fn__8612.invoke(io.clj:169)
	at clojure.java.io$fn__8551$G__8546__8558.invoke(io.clj:73)
	at clojure.java.io$reader.doInvoke(io.clj:106)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at incanter.io$read_dataset.doInvoke(io.clj:66)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at bcbio.rnaseq.simulator__init.load(Unknown Source)
	at bcbio.rnaseq.simulator__init.<clinit>(Unknown Source)
	... 52 more

**Comment by roryk** [comment]
Hi @kspham,

It looks like some of the files are missing, it is missing baseprop.tsv, but that should be there. Does /bin/bcbio-rnaseq/resources/comparisons/baseprop.tsv not exist?

**Comment by kspham** [comment]
THanks Roryk, I installed the latest version and this error goes away :)
